version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sklad:/app
    command: >
      sh -c "pipenv run python3 manage.py migrate &&
             pipenv run python3 manage.py wait_for_db &&
             pipenv run python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.8-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: pipenv run celery -A config worker --loglevel=debug --concurrency=4
    volumes:
      - ./sklad:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app

  celery_cron:
    restart: always
    build:
      context: .
    command: pipenv run celery -A config beat
    volumes:
      - ./sklad:/app
    env_file:
    - ./.env.dev
    depends_on:
      - db
      - redis
      - app