version: '3'
 
services:
  app:
    command: >
      sh -c "pipenv run python3 manage.py wait_for_db &&
             pipenv run python3 manage.py migrate &&
             pipenv run python3 manage.py init_db &&
             pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
#    volumes:
#      - ./sklad:/app
    env_file:
      - ./.env.prod
    networks: # <-- here
      - nginx_network
      - db_network

  db:
    env_file:
      - ./.env.prod
    networks: # <-- here
      - db_network

  celery:
    command: pipenv run celery -A config worker --concurrency=4
    env_file:
      - ./.env.prod
    networks: # <-- here
      - db_network

  celery_cron:
    env_file:
      - ./.env.prod
    networks: # <-- here
      - db_network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
    networks: # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge