version: '3'
 
services:
  app:
    ports:
      - "80:80"
    volumes:
      - ./sklad:/app
    env_file:
      - ./.env.prod

  db:
    env_file:
      - ./.env.prod

  celery:
    command: pipenv run celery -A config worker --concurrency=4
    env_file:
      - ./.env.prod

  celery_cron:
    env_file:
      - ./.env.prod
