version: '3'
 
services:
  app:
    build:
      context: .
    command: >
      sh -c "pipenv run python3 manage.py migrate &&
             pipenv run python3 manage.py wait_for_db &&
             pipenv run python3 manage.py runserver 0.0.0.0:80"
    depends_on:
      - db

  db:
    image: postgres:13.8-alpine
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./sklad:/app
    depends_on:
      - db
      - redis
      - app

  celery_cron:
    restart: always
    build:
      context: .
    command: pipenv run celery -A config beat
    volumes:
      - ./sklad:/app
    depends_on:
      - db
      - redis
      - app