version: '3'
 
services:
  app:
    ports:
      - "8000:8000"
    command: >
      sh -c "pipenv run python3 manage.py wait_for_db &&
             pipenv run python3 manage.py migrate &&
             pipenv run python3 manage.py init_db &&
             pipenv run python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./sklad:/app
    env_file:
      - ./.env.dev

  db:
    env_file:
      - ./.env.dev

  celery:
    command: pipenv run celery -A config worker --loglevel=debug --concurrency=4
    env_file:
      - ./.env.dev

  celery_cron:
    env_file:
      - ./.env.dev