version: '3'
 
services:
  app:
    build:
      context: .
    depends_on:
      - db

  db:
    image: postgres:13.8-alpine

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./sklad:/app
    depends_on:
      - db
      - redis

  celery_cron:
    restart: always
    build:
      context: .
    command: pipenv run celery -A config beat
    volumes:
      - ./sklad:/app
    depends_on:
      - db
      - redis