# Generated by Django 4.1.1 on 2022-09-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('vl', 'На проверке'), ('fi', 'Завершен'), ('ca', 'Отменен')], default='vl', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article', models.IntegerField(unique=True)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('vl', 'На проверке'), ('fi', 'Завершен'), ('ca', 'Отменен')], default='vl', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qr', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.buyer')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('fio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('category', models.ManyToManyField(to='sklad.category')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.category')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.nomenclature')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='content',
            field=models.ManyToManyField(through='sklad.ShipmentContent', to='sklad.nomenclature'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.subcategory'),
        ),
        migrations.CreateModel(
            name='DeliveryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.delivery')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.nomenclature')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='content',
            field=models.ManyToManyField(through='sklad.DeliveryContent', to='sklad.nomenclature'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.vendor'),
        ),
    ]
