# Generated by Django 4.1.1 on 2022-10-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(verbose_name='Номер счета')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Наименование банка')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('va', 'Проверка'), ('ca', 'Отменен'), ('co', 'Собран'), ('fi', 'Завершен')], default='va', max_length=2, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления статуса')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('article', models.IntegerField(unique=True, verbose_name='Артукул')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('contactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sklad.contactor')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
            bases=('sklad.contactor',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='DocumentNomenclatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.document', verbose_name='Заявка')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.nomenclature', verbose_name='Номенклатура')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='nomenclatures',
            field=models.ManyToManyField(through='sklad.DocumentNomenclatures', to='sklad.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('contactor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sklad.contactor')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.bankdetails', verbose_name='Банковские реквизиты')),
                ('category', models.ManyToManyField(to='sklad.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
            bases=('sklad.contactor',),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sklad.buyer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='document',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sklad.vendor', verbose_name='Поставщик'),
        ),
    ]
