# Generated by Django 4.1.1 on 2022-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnomenclatures',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
