# Generated by Django 4.1.1 on 2022-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcontent',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
