# Generated by Django 4.1.1 on 2022-10-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_alter_documentnomenclatures_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='number',
        ),
    ]
