# Generated by Django 4.1.1 on 2022-10-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_remove_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklad.buyer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='document',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklad.vendor', verbose_name='Поставщик'),
        ),
    ]
