# Generated by Django 4.1.1 on 2022-10-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_document_buyer_alter_document_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sklad.bankdetails', verbose_name='Банковские реквизиты'),
        ),
    ]
