# Generated by Django 4.1.2 on 2022-10-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_alter_vendor_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
