# Generated by Django 4.1.2 on 2022-10-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_alter_store_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='category',
            new_name='categories',
        ),
    ]
