# Generated by Django 4.1.2 on 2022-10-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0004_alter_store_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nomenclature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
    ]
