# Generated by Django 4.1.2 on 2022-10-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.nomenclature', unique=True, verbose_name='Номенклатура'),
        ),
    ]
