# Generated by Django 4.1.2 on 2022-10-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentnomenclatures',
            options={'verbose_name': 'Номенклатура документа', 'verbose_name_plural': 'Номенклатура документа'},
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
