# Generated by Django 4.1.2 on 2022-10-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactor', '0001_initial'),
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('va', 'Проверка'), ('ca', 'Отменен'), ('co', 'Собран'), ('fi', 'Завершен')], default='va', max_length=2, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления статуса')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contactor.buyer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='DocumentNomenclatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document', verbose_name='Заявка')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclature.nomenclature', verbose_name='Номенклатура')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='nomenclatures',
            field=models.ManyToManyField(through='document.DocumentNomenclatures', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='document',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contactor.vendor', verbose_name='Поставщик'),
        ),
    ]
