# Generated by Django 4.1.2 on 2022-10-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactor', '0003_alter_person_options_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactor.person', verbose_name='Покупатель'),
        ),
    ]
