# Generated by Django 4.1.2 on 2022-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactor', '0007_alter_bankdetails_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='Телефон'),
        ),
    ]
