# Generated by Django 4.1.2 on 2022-10-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Банковские реквизиты', 'verbose_name_plural': 'Банковские реквизиты'},
        ),
    ]
