# Generated by Django 4.1.2 on 2022-10-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactor', '0004_alter_buyer_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account',
            field=models.IntegerField(unique=True, verbose_name='Номер счета'),
        ),
    ]
